version: '3.3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///./store.sqlite3
      - GUNICORN_PORT=5000
    command: >
      sh -c "flask db upgrade -d core/migrations/ &&
             gunicorn -c gunicorn_config.py core.server:app"